import os
import sys

import streamlit as st
from dotenv import load_dotenv

load_dotenv()

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if ROOT not in sys.path:
    sys.path.insert(0, ROOT)

from components.sidebar import render_sidebar

st.set_page_config(
    page_title="Yelp Streaming Analytics",
    page_icon="📊",
    layout="wide",
    menu_items={},
)

render_sidebar()

st.title("Yelp Streaming Analytics")
st.markdown("""
Welcome to the Yelp Streaming Analytics Dashboard.

Use the sidebar to navigate:
- **Overview** — Charts and statistics from BigQuery
- **AI Insights** — Business insights generated by Cerebras AI
- **Pipeline Status** — Current state of the data pipeline
""")
