import os
import sys

import streamlit as st
from dotenv import load_dotenv

load_dotenv()

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
if ROOT not in sys.path:
    sys.path.insert(0, ROOT)

from components.sidebar import render_sidebar
from dynamodb.cache_manager import get_insights_by_category, get_insights_grouped_by_date
from cerebras.insight_generator import (
    generate_category_performance,
    generate_review_engagement,
    generate_regional_competition,
    generate_sentiment_depth,
    generate_all_insights,
)

st.set_page_config(page_title="AI Insights — Yelp Analytics", layout="wide")

render_sidebar()

st.title("AI Insights")
st.markdown("Business insights generated by **Cerebras gpt-oss-120b** from BigQuery analytics data.")

# ── Generate All button ───────────────────────────────────────────────────────
if st.button("Generate All Insights", type="primary"):
    with st.spinner("Running all 4 categories via Cerebras API..."):
        try:
            generate_all_insights()
            st.success("All insights generated and saved to DynamoDB.")
            st.rerun()
        except Exception as e:
            st.error(f"Failed to generate all insights: {e}")

st.markdown("---")


# ── Helpers ───────────────────────────────────────────────────────────────────

def render_insight_card(item: dict, index: int) -> None:
    with st.container(border=True):
        col_meta, col_src = st.columns([3, 1])
        with col_meta:
            st.caption(f"#{index} · {item.get('created_at', '')[:19].replace('T', ' ')} UTC")
        with col_src:
            st.caption(item.get("source", ""))
        st.markdown(item.get("insight_text", ""))


def render_category_tab(category: str, label: str, generate_fn) -> None:
    try:
        items = get_insights_by_category(category)
    except Exception as e:
        st.error(f"Failed to load from DynamoDB: {e}")
        return

    col_btn, _ = st.columns([2, 8])
    with col_btn:
        if st.button(f"Generate {label}", key=f"btn_{category}"):
            with st.spinner(f"Calling Cerebras API for {label}..."):
                try:
                    generate_fn()
                    st.success(f"{label} insight saved.")
                    st.rerun()
                except Exception as e:
                    st.error(f"Failed: {e}")

    if not items:
        st.info(f"No {label} insights yet. Click the button above to generate.")
        return

    for i, item in enumerate(items, 1):
        render_insight_card(item, i)


# ── Tabs ──────────────────────────────────────────────────────────────────────

tab1, tab2, tab3, tab4, tab5 = st.tabs([
    "Category Performance",
    "Review Engagement",
    "Regional Competition",
    "Sentiment Depth",
    "History",
])

with tab1:
    st.subheader("Category Performance")
    st.caption("Which business categories consistently receive higher ratings?")
    render_category_tab("category_performance", "Category Performance", generate_category_performance)

with tab2:
    st.subheader("Review Engagement")
    st.caption("How does review length and social engagement (useful/funny/cool) vary by star rating?")
    render_category_tab("review_engagement", "Review Engagement", generate_review_engagement)

with tab3:
    st.subheader("Regional Competition")
    st.caption("How does market density relate to customer satisfaction across cities?")
    render_category_tab("regional_competition", "Regional Competition", generate_regional_competition)

with tab4:
    st.subheader("Sentiment Depth")
    st.caption("What distinguishes negative reviews from positive ones in length and usefulness?")
    render_category_tab("sentiment_depth", "Sentiment Depth", generate_sentiment_depth)

with tab5:
    st.subheader("Insight History")
    st.caption("All generated insights grouped by date.")
    try:
        grouped = get_insights_grouped_by_date()
        if not grouped:
            st.info("No insights found.")
        else:
            for date in sorted(grouped.keys(), reverse=True):
                items = grouped[date]
                with st.expander(f"{date} — {len(items)} insight(s)", expanded=False):
                    for item in items:
                        label = item.get("category_label", item.get("category", "general"))
                        st.markdown(f"**{label}** · {item.get('created_at', '')[:19].replace('T', ' ')} UTC")
                        st.markdown(item.get("insight_text", ""))
                        st.markdown("---")
    except Exception as e:
        st.error(f"Failed to load insight history: {e}")
